name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  echo:
    runs-on: ubuntu-18.04
    steps:
      - run: echo 'Hello, GitHub Actions!'
  checkout:
    runs-on: ubuntu-18.04
    steps:
      - run: ls -al