name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  echo:
    runs-on: ubuntu-18.04
    steps:
      - run: echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-18.04
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al